### ISSUE TITLE
installation in code-server not possible.

### ISSUE THREAD

**Issue by rowanfuchs** [mobalic/jetbrains-dark-theme#1]
The extension doesn't seem to be available within [code-server](https://github.com/coder/code-server) which is VS code but then within the browser however it uses an open extension marketplace, could you make it also available on [open-vsx](https://open-vsx.org) so that it's installable?

Thank you in advance!

**Comment by mobalti** [comment]
Thanks for creating the issue! I have made the extension available on [Open-VSX](https://open-vsx.org/extension/MoBalic/jetbrains-dark-theme).
If you encounter any issues, please let me know. Happy coding!

**Comment by rowanfuchs** [comment]
Awesome, thank you so much for your effort!
